#!/bin/bash
echo $1 |
sed  's/½/ one half /g' | 
sed  's/1\/2/ one half /g' | 
sed  's/⅓/ one third /g' | 
sed  's/1\/3/ one third /g' |
sed  's/¼/ one quarter /g' |
sed  's/1\/4/ one quarter /g' |
sed  's/⅕/ one fith /g' |
sed  's/1\/5/ one fith /g' |
sed  's/⅙/ one sixth /g' |
sed  's/1\/6/ one sixth /g' |
sed  's/⅐/ one seventh /g' |
sed  's/1\/7/ one seventh /g' |
sed  's/⅛/ one eigth /g' |
sed  's/1\/8/ one eigth /g' |
sed  's/⅑/ one ninth /g' |
sed  's/1\/9/ one ninth /g' |
sed  's/⅒/ one tenth /g' |
sed  's/1\/10/ one tenth /g' |
sed  's/⅔/ two third /g' | 
sed  's/2\/3/ two third /g' |
sed  's/⅖/ two fith /g' |
sed  's/2\/5/ two fith /g' |
sed  's/¾/ three quarter /g' |
sed  's/3\/4/ three quarter /g' |
sed  's/⅗/ three fith /g' |
sed  's/3\/5/ three fith /g' |
sed  's/⅜/ three eigth /g' |
sed  's/3\/8/ three eigth /g' |
sed  's/⅘/ four fith /g' |
sed  's/4\/5/ four fith /g' |
sed  's/⅚/ five sixth /g' |
sed  's/5\/6/ five sixth /g' |
sed  's/⅞/ seven eigth /g' |
sed  's/7\/8/ seven eigth /g' |
sed  's/⅝/ five eigth /g' |
sed  's/5\/8/ five eigth /g' 
