#!/bin/bash 
OUTPUT="$(cat INGED)"
echo $OUTPUT
#echo "https://www.allrecipes.com/search/results/?wt=$OUTPUT&ingIncl=" > INGED
OUTPUT2="$(echo "$1 $2 $3 $4 $5 $6 $7 $8"  | sed 's/^[ \t]*//' )"
echo $OUTPUT2
echo "$OUTPUT$OUTPUT2&sort=re"
OUTPUT3="$(lynx -dump "$OUTPUT$OUTPUT2&sort=re")"

echo $OUTPUT3 | #) 
grep "https://www.allrecipes.com/recipe/" | 
cut -d"." -f2- |
sed '/^$/d' |
sed '$!N; /^\(.*\)\n\1$/!P; D' > tmp_URL

 cat tmp_URL | tr " "  "\n" |sed $'s/https:\/\/www.allrecipes.com\/recipe/\\\/g' | cut -d/ -f3 | tr "-" " " | sed '/^$/d' | sed -ne 's/$/ .. &/p' |  nl -bt -s ... #> tmp_recipe

 
 
