#!/bin/bash
INPUT=$(sed "$1!d" tmp_URL)  ## e comment out 2nd and 3rd line and uncomment  3 to test  web address formating
URL="$( echo -e $INPUT | sed 's/\?.*//' )"
 
#echo $1 

echo  $URL 
FILE="$( echo -e  $URL | tr  '/' ' ' |  awk '{print $NF}' )"
echo $FILE 
TITLE="$( echo $FILE | tr '-' ' ' )"
echo $TITLE
LINE="'$TITLE': join(abspath(dirname(__file__)), 'recipes', '$FILE'),"
echo $LINE
NO_WHITESPACE="$(echo -e "${LINE}" | tr -d '[:space:]')"

DATA="$(grep "'$TITLE': join(abspath(dirname(__file__)), 'recipes', '$FILE')," $HOME/mycroft-core/skills/all-recipes-skill/__init__.py) "
NO_WHITESPACE1="$(echo -e "${DATA}" | tr -d '[:space:]')"
#echo $DATA
#echo $NO_WHITESPACE
if [[ $NO_WHITESPACE1 == $NO_WHITESPACE ]]
   then
         echo "exist already "
     else
sed -i "/^        self.play_list = {/a\            $LINE" $HOME/mycroft-core/skills/all-recipes-skill/__init__.py
echo $TITLE >> $HOME/mycroft-core/skills/all-recipes-skill/vocab/en-us/title.entity


echo  Saving to $HOME/mycroft-core/skills/all-recipes-skill/recipes/$FILE 

$HOME/mycroft-core/skills/all-recipes-skill/process_recipe $URL |

sed  "1s/^/$TITLE\n\n /" > $HOME/mycroft-core/skills/all-recipes-skill/recipes/$FILE 

PIC="$(cat PIC_URL)"

wget -O $HOME/mycroft-core/skills/all-recipes-skill/recipes/pics/$FILE $PIC

#sed -i "1s/^/$TITLE\n\n /" $HOME/AllRecipes/$FILE

fi
